# Generated by Django 5.1.4 on 2024-12-14 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absecapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
    ]
