# Generated by Django 5.1.4 on 2024-12-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absecapp', '0003_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='11111', max_length=30),
        ),
    ]
