# Generated by Django 5.1.4 on 2024-12-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absecapp', '0005_file_created_at_file_owner_file_shared_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_loggedin',
            field=models.BooleanField(default=False),
        ),
    ]
